version: '3'

services:
  db:
    image: mongo:3.6
    ports:
      - 27017:27017

  cli:
    build: ./cli
    command: load
    environment:
      - 'MONGO_URI=mongodb://db:27017'
    depends_on:
      - db

  mongo_express:
    image: mongo-express
    links:
      - db:mongo
    ports:
      - 8081:8081
