version: '3'

services:
  db:
    image: mongo:3.6
    ports:
      - 27017:27017

  cli:
    build: ./cli
    command: "load 200"
    environment:
      - 'MONGO_URI=mongodb://db:27017'
    depends_on:
      - db

  api:
    build: ./api
    environment:
      - 'MONGO_URI=mongodb://db:27017/test'
      - 'APPLICATION_SECRET=ecabbd83-beaa-4a30-9c36-a7a79bdf0afd'
    depends_on:
      - db
    ports:
      - 9000:9000

  mongo_express:
    image: mongo-express
    links:
      - db:mongo
    ports:
      - 8081:8081
